# Generated by Django 3.2 on 2022-05-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.TextField()),
                ('user_id', models.IntegerField()),
                ('payment_id', models.TextField()),
                ('paid', models.TextField()),
                ('user_name', models.TextField()),
                ('pyament_status', models.TextField()),
                ('amount', models.TextField()),
                ('user_email', models.TextField()),
                ('user_package', models.TextField()),
                ('customer_id', models.TextField()),
                ('type', models.TextField()),
                ('created', models.TextField()),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
