# Generated by Django 3.2.11 on 2022-07-28 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_stripecustomer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stripecustomer',
            table=None,
        ),
    ]
