# Generated by Django 3.2.11 on 2022-07-28 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_stripecustomer_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='paymentrecord',
            table='old_payment',
        ),
    ]
