# Generated by Django 3.2.11 on 2022-07-28 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_paymentrecord_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='paymentrecord',
            table='payment',
        ),
    ]
