# Generated by Django 3.2.11 on 2022-07-29 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_paymentrecord_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StripeCustomer',
        ),
    ]
