# Generated by Django 2.2.5 on 2019-10-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleepdiary',
            name='week_day',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
