# Generated by Django 2.2.5 on 2019-11-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20191031_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleepdiary',
            name='day_avg',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
