# Generated by Django 3.2 on 2022-06-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20220613_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleepdiary',
            name='total_gotup_time',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
