# Generated by Django 3.2 on 2022-07-26 13:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_providercard'),
    ]

    operations = [
        migrations.AddField(
            model_name='providercard',
            name='subscription_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
