# Generated by Django 2.2.2 on 2019-07-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190718_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='driving_license_back_img',
            field=models.CharField(max_length=100),
        ),
    ]
