# Generated by Django 2.2.2 on 2019-08-09 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190718_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verifiedcode',
        ),
    ]
