# Generated by Django 2.2.5 on 2019-11-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_verifiedcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='package_no',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='verifiedcode',
            field=models.CharField(default='', max_length=20),
        ),
    ]
