# Generated by Django 2.2.5 on 2019-11-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_patientpaymentdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='driving_license_back_img',
            field=models.ImageField(default='default.png', upload_to='user_pics'),
        ),
    ]
