# Generated by Django 2.2.5 on 2019-11-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20191113_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='provider_image',
            field=models.ImageField(default='default.png', upload_to='user_pics'),
        ),
    ]
