# Generated by Django 2.2.5 on 2019-11-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_patientprofile_provider_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='verifiedcode',
            field=models.CharField(default='', max_length=30),
        ),
    ]
