# Generated by Django 3.2 on 2022-05-25 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_user_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=20)),
                ('driving_license_front_img', models.ImageField(default='/media/default.png', upload_to='user_pics')),
                ('driving_license_back_img', models.ImageField(default='/media/default.png', upload_to='user_pics')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('package_no', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'patients',
            },
        ),
        migrations.CreateModel(
            name='RefPatient',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('provider_id', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=20)),
                ('driving_license_front_img', models.ImageField(default='/media/default.png', upload_to='user_pics')),
                ('driving_license_back_img', models.ImageField(default='/media/default.png', upload_to='user_pics')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('package_no', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ref_patients',
            },
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='is_provider',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='package_no',
        ),
        migrations.RemoveField(
            model_name='user',
            name='packageno',
        ),
        migrations.AddField(
            model_name='user',
            name='active_patient',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='package',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='role_id',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='doctor_ref_number',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=20)),
                ('license_state', models.CharField(max_length=20)),
                ('type_of_practice', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('practice_name', models.CharField(max_length=50)),
                ('practice_phone_number', models.CharField(max_length=20)),
                ('practice_address', models.CharField(max_length=200)),
                ('driving_license_front_img', models.ImageField(default='/media/default.png', upload_to='user_pics')),
                ('driving_license_back_img', models.ImageField(default='/media/default.png', upload_to='user_pics')),
                ('provider_image', models.ImageField(default='/media/default.png', upload_to='user_pics')),
                ('fax_no', models.CharField(max_length=20)),
                ('primary_care_office_name', models.CharField(max_length=100)),
                ('primary_care_doctor_name', models.CharField(max_length=100)),
                ('provider_ref', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'providers',
            },
        ),
    ]
