# Generated by Django 3.2.11 on 2022-08-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20220525_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='subscription_status',
            field=models.CharField(max_length=50, null=True),
        ),

    ]
