# Generated by Django 3.2.11 on 2022-08-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20220818_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='total_patients',
            field=models.IntegerField(default=0),
        ),
    ]
