# Generated by Django 3.2.11 on 2022-08-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_provider_total_patients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='subscription_status',
        ),
        migrations.AddField(
            model_name='provider',
            name='sub_status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
