# Generated by Django 3.2.11 on 2022-08-18 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20220818_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='sub_status',
            new_name='subscription_status',
        ),
    ]
