# Generated by Django 3.2.9 on 2023-03-22 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taketester', '0002_auto_20230321_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='options_new',
            old_name='Question_new',
            new_name='question_new',
        ),
        migrations.RemoveField(
            model_name='question_new',
            name='answer',
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_selected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taketester.options_new')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taketester.question_new')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
