# Generated by Django 2.2.5 on 2019-10-28 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepDiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_went_to_bed', models.TimeField()),
                ('time_fell_asleep', models.TimeField()),
                ('time_got_up', models.TimeField()),
                ('no_of_times_awakend', models.IntegerField()),
                ('total_time_awakened', models.IntegerField()),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
