# Generated by Django 2.2.5 on 2019-10-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20191028_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleepdiary',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
