# Generated by Django 2.2.5 on 2019-10-31 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20191028_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleepdiary',
            name='is_updated',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sleepdiary',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sleepdiary',
            name='no_of_times_awakend',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sleepdiary',
            name='time_fell_asleep',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='sleepdiary',
            name='time_got_up',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='sleepdiary',
            name='time_went_to_bed',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='sleepdiary',
            name='total_time_awakened',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sleepdiary',
            name='week_day',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
