# Generated by Django 2.2.5 on 2019-11-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_sleepdiary_day_avg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleepdiary',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
