# Generated by Django 3.2 on 2022-05-25 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0008_auto_20191109_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.TextField()),
                ('content', models.TextField()),
                ('review_content', models.TextField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'video_sessions',
            },
        ),
        migrations.CreateModel(
            name='VideoSessionsCompleted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('completed', models.BooleanField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'video_session_patients',
            },
        ),
        migrations.CreateModel(
            name='VideoViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('view_video', models.IntegerField()),
            ],
            options={
                'db_table': 'video_views',
            },
        ),
        migrations.AddField(
            model_name='sleepdiary',
            name='out_of_bed',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='VideoQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('main_question', models.TextField()),
                ('correct_ans', models.TextField()),
                ('options', models.TextField()),
                ('status', models.IntegerField()),
                ('type', models.IntegerField(default=1)),
                ('video_sessions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.videosessions')),
            ],
            options={
                'db_table': 'video_questions',
            },
        ),
        migrations.CreateModel(
            name='VideoAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video_questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.videoquestions')),
            ],
            options={
                'db_table': 'video_answers',
            },
        ),
    ]
