# Generated by Django 3.2 on 2022-05-25 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20220525_1716'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='videoviews',
            table='patient_video_view',
        ),
    ]
