# Generated by Django 3.2 on 2022-07-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_sleepdiary_total_gotup_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.CharField(max_length=5)),
                ('name_on_card', models.CharField(max_length=40)),
                ('exp_date', models.DateField()),
                ('cvc_code', models.CharField(max_length=3)),
                ('card_number', models.CharField(max_length=18)),
            ],
            options={
                'db_table': 'provider_card_detail',
            },
        ),
    ]
